apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: backend-feed
  name: backend-feed
spec:
  selector:
    matchLabels:
      service: backend-feed
  replicas: 2
  template:
    metadata:
      labels:
        service: backend-feed
    spec:
      containers:
        - name: backend-feed
          image: docker.io/ramshadows/udagram-api-feed:latest
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "500m"
            limits:
              cpu: "600m"
          envFrom:
            - secretRef:
                name: env-secret
                optional: false
            - configMapRef:
                name: my-configmap
                optional: false
