apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: EKS-Demo-Cluster-2
  region: us-east-1

vpc:
  id: vpc-03740bf62e092a6b5
  cidr: "10.0.0.0/16"
  subnets:
    public:
      us-east-1b:
        id: subnet-0926ef5a5527eef87
      us-east-1a:
        id: subnet-0beb3394403d59c5a
    #private:
    #  us-east-1b:
    #   id: subnet-04c3747826d8c05b4
    #  us-east-1a:
    #   id: subnet-07d931aa9cc40b274

nodeGroups:
  - name: EKS-public-workers
    instanceType: m5.large
    desiredCapacity: 2
  #- name: EKS-private-workers
  #  instanceType: t2.medium
  #  desiredCapacity: 1
  #  privateNetworking: false