apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy
  labels:
    service: reverseproxy
spec:
  replicas: 2
  selector:
    matchLabels:
      service: reverseproxy
  template:
    metadata:
      labels:
        service: reverseproxy
    spec:
      containers:
        - image: docker.io/ramshadows/reverseproxy:v8
          name: reverseproxy
          imagePullPolicy: Always
          resources:
            requests:
              memory: "100Mi"
            limits:
              memory: "200Mi"
          command: ["stress"]
          args: ["--vm", "1", "--vm-bytes", "150M", "--vm-hang", "1"]
          ports:
            - containerPort: 8080
      restartPolicy: Always
