apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy
  labels:
    service: reverseproxy
spec:
  replicas: 2
  selector:
    matchLabels:
      service: reverseproxy
  template:
    metadata:
      labels:
        service: reverseproxy
    spec:
      containers:
        - image: docker.io/ramshadows/reverseproxy:v12
          name: reverseproxy
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 250m
            limits:
              cpu: 500m
          ports:
            - containerPort: 8080
      restartPolicy: Always
