apiVersion: v1
kind: Service
metadata:
  name: reverseproxy
  labels:
    service: reverseproxy
spec:
  ports:
    - port: 8080
      name: "8081"
      targetPort: 8080
  selector:
    service: reverseproxy
