apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-reverseproxy
  labels:
    service: udagram-reverseproxy
spec:
  replicas: 2
  selector:
    matchLabels:
      service: udagram-reverseproxy
  template:
    metadata:
      labels:
        service: udagram-reverseproxy
    spec:
      containers:
        - image: ramshadows/udagram-reverseproxy:v4
          name: reverseproxy
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "80m"
            limits:
              memory: "1024Mi"
              cpu: "80m"
          ports:
            - containerPort: 8080
      restartPolicy: Always
