name: Build and Publish

on:
  # run it on push to the default repository branch
  push:
    branches: [main]
  # run it during pull request
  pull_request:
    branches: [main]

jobs:
  # define job to build and publish docker image
  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-latest
    

    # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # setup Docker buld action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push udagram-api-feed image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./udagram-api-feed/Dockerfile
          tags: |
            ramshadows/udagram-api-feed:v3
            ghcr.io/ramshadows/udagram-api-feed:v4
          # build on feature branches, push only on main branch
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build and Push udagram-api-user image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./udagram-api-user/Dockerfile
          tags: |
            ramshadows/udagram-api-user:v4
            ghcr.io/ramshadows/udagram-api-user:v3
          # build on feature branches, push only on main branch
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build and Push udagram-frontend image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./udagram-frontend/Dockerfile
          tags: |
            ramshadows/udagram-frontend:v5
            ghcr.io/ramshadows/udagram-frontend:v5
          # build on feature branches, push only on main branch
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build and Push udagram-reverseproxy image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./udagram-reverseproxy/Dockerfile
          tags: |
            ramshadows/udagram-reverseproxy:v5
            ghcr.io/ramshadows/udagram-reverseproxy:v5
          # build on feature branches, push only on main branch
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
